require: rubocop-performance

AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - node_modules/**/*
  NewCops: disable

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineLength:
  Max: 120
  Exclude:
    - config/routes.rb
    - config/routes/*
    - db/migrate/*

Lint/RaiseException:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - spec/**/*
    - test/**/*

Metrics/BlockLength:
  Exclude:
    - config/initializers/*
    - config/routes.rb
    - Gemfile
    - spec/**/*
    - test/**/*
    - "*.gemspec"
    - "**/*.rake"

Metrics/BlockNesting:
  Exclude:
    - spec/**/*
    - test/**/*

Metrics/CyclomaticComplexity:
  Exclude:
    - spec/**/*
    - test/**/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*
    - spec/**/*
    - test/**/*
  CountAsOne:
    - hash
    - array
    - heredoc

Metrics/ModuleLength:
  Exclude:
    - spec/**/*
    - test/**/*

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AndOr:
  EnforcedStyle: conditionals

Style/DateTime:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Lambda:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': ()
    '%I': ()
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': ()
    '%W': ()
    '%x': ()

Style/SlicingWithRange:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true
