Documentation:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Metrics/LineLength:
  Max: 100

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': ()
    '%I': ()
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': ()
    '%W': ()
    '%x': ()

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true
